-- =============================================================================
-- Container Market GR — Migration 004: Seed listings from listings.json
-- Author: Katsoulakis
-- Date: 2026-07-04
-- Project: conteiner-market
-- File: 20260704030000_seed_listings.sql
-- Description: Initial catalog data (idempotent on slug)
-- =============================================================================

insert into listings (
  slug, type, condition, condition_en, price, price_formatted,
  unit, unit_en, location, location_en, listing_type,
  stock_condition, is_offer, image, images, description, description_en, active
) values
  ('20ft-dry', '20ft Dry', 'Cargo Worthy', 'Cargo Worthy', 2800, '€2.800', null, null, 'Έδρα μας — Ελλάδα', 'Our headquarters — Greece', 'sale'::listing_type, 'used'::stock_condition, true, 'https://images.pexels.com/photos/1267338/pexels-photo-1267338.jpeg?auto=compress&cs=tinysrgb&w=1200', '["https://images.pexels.com/photos/1267338/pexels-photo-1267338.jpeg?auto=compress&cs=tinysrgb&w=1200","https://images.pexels.com/photos/4484078/pexels-photo-4484078.jpeg?auto=compress&cs=tinysrgb&w=1200"]'::jsonb, '20ft dry van container, cargo worthy, wind & water tight. Ιδανικό για αποθήκευση, μεταφορές και μετατροπές (γραφείο, workshop). Διαθέσιμο από την έδρα μας — παράδοση σε όλη την Ελλάδα. Άμεση επαφή, χωρίς ενδιάμεσους.', '20ft dry van container, cargo worthy, wind & water tight. Ideal for storage, logistics, and conversions (office, workshop). Available from our headquarters — nationwide delivery. Direct contact, no middlemen.', true),
  ('40ft-dry', '40ft Dry', 'Grade A', 'Grade A', 3600, '€3.600', null, null, 'Έδρα μας — Ελλάδα', 'Our headquarters — Greece', 'sale'::listing_type, 'used'::stock_condition, false, 'https://images.pexels.com/photos/4484078/pexels-photo-4484078.jpeg?auto=compress&cs=tinysrgb&w=1200', '["https://images.pexels.com/photos/4484078/pexels-photo-4484078.jpeg?auto=compress&cs=tinysrgb&w=1200","https://images.pexels.com/photos/262353/pexels-photo-262353.jpeg?auto=compress&cs=tinysrgb&w=1200"]'::jsonb, '40ft dry container Grade A — εξωτερικά/εσωτερικά σε πολύ καλή κατάσταση. Μεγάλος χώρος για αποθήκη, εργοτάξιο ή σταθερή εγκατάσταση. Cargo worthy, κατάλληλο για εμπορεύματα και μακροχρόνια χρήση. Παράδοση από την έδρα μας.', '40ft dry container Grade A — exterior/interior in very good condition. Large space for warehouse, job site, or permanent setup. Cargo worthy, suitable for goods and long-term use. Delivery from our base.', true),
  ('40ft-high-cube', '40ft High Cube', 'Καινούριο', 'New', 4200, '€4.200', null, null, 'Έδρα μας — Ελλάδα', 'Our headquarters — Greece', 'sale'::listing_type, 'new'::stock_condition, true, 'https://images.pexels.com/photos/1214218/pexels-photo-1214218.jpeg?auto=compress&cs=tinysrgb&w=1200', '["https://images.pexels.com/photos/1214218/pexels-photo-1214218.jpeg?auto=compress&cs=tinysrgb&w=1200"]'::jsonb, '40ft High Cube — επιπλέον ύψος (+30cm) για bulky φορτία και αποθήκευση. Καινούριο container, ιδανικό για logistics, αποθήκες και projects που χρειάζονται maximum όγκο. ISO standard, άμεση διαθεσιμότητα από εμάς.', '40ft High Cube — extra height (+30cm) for bulky cargo and storage. New container, ideal for logistics, warehouses, and volume-heavy projects. ISO standard, immediately available from us.', true),
  ('20ft-reefer', '20ft Reefer', 'Ψυγείο', 'Refrigerated', 320, '€320', '/μήνα', '/month', 'Έδρα μας — Ελλάδα', 'Our headquarters — Greece', 'rent'::listing_type, 'used'::stock_condition, true, 'https://images.pexels.com/photos/906494/pexels-photo-906494.jpeg?auto=compress&cs=tinysrgb&w=1200', '["https://images.pexels.com/photos/906494/pexels-photo-906494.jpeg?auto=compress&cs=tinysrgb&w=1200"]'::jsonb, '20ft refrigerated container (reefer) προς ενοικίαση. Ελεγχόμενη θερμοκρασία για τρόφιμα, φάρμακα, λουλούδια και ευαίσθητα προϊόντα. Μηνιαία μίσθωση, ευέλικτοι όροι. Τεχνικός έλεγχος πριν την παράδοση — ρωτήστε μας για διαθεσιμότητα.', '20ft refrigerated container (reefer) for rent. Temperature-controlled for food, pharmaceuticals, flowers, and sensitive goods. Monthly lease, flexible terms. Technical check before delivery — contact us for availability.', true),
  ('20ft-open-top', '20ft Open Top', 'Ανοιχτό', 'Open top', 190, '€190', '/μήνα', '/month', 'Έδρα μας — Ελλάδα', 'Our headquarters — Greece', 'rent'::listing_type, 'used'::stock_condition, false, '/images/containers/20ft-open-top.jpg', '["/images/containers/20ft-open-top.jpg","https://images.pexels.com/photos/163726/cargo-containers-boxes-shipment-163726.jpeg?auto=compress&cs=tinysrgb&w=1200"]'::jsonb, '20ft open top container — αφαιρούμενο/ύφασμα οροφής για φόρτωση από πάνω (γερανός). Ιδανικό για μηχανήματα, υπερμεγέθη αντικείμενα και project cargo. Ενοικίαση ανά μήνα, παράδοση σε όλη την Ελλάδα.', '20ft open top container — removable/tarpaulin roof for top loading (crane). Ideal for machinery, oversized items, and project cargo. Monthly rental, delivery across Greece.', true),
  ('45ft-pallet-wide', '45ft Pallet Wide', 'Καινούριο', 'New', 5400, '€5.400', null, null, 'Έδρα μας — Ελλάδα', 'Our headquarters — Greece', 'sale'::listing_type, 'new'::stock_condition, false, 'https://images.pexels.com/photos/262353/pexels-photo-262353.jpeg?auto=compress&cs=tinysrgb&w=1200', '["https://images.pexels.com/photos/262353/pexels-photo-262353.jpeg?auto=compress&cs=tinysrgb&w=1200"]'::jsonb, '45ft pallet wide — ευρύτερο εσωτερικό για 2.500×1.244m pallets (euro pallets). Καινούριο, για logistics και διανομές μεγάλου όγκου. Cargo worthy, άμεση παράδοση από την έδρα μας.', '45ft pallet wide — wider interior for 2.500×1.244m pallets (euro pallets). New, for high-volume logistics and distribution. Cargo worthy, immediate delivery from our base.', true),
  ('40ft-reefer', '40ft Reefer', 'Grade A', 'Grade A', 480, '€480', '/μήνα', '/month', 'Έδρα μας — Ελλάδα', 'Our headquarters — Greece', 'rent'::listing_type, 'used'::stock_condition, false, 'https://images.pexels.com/photos/163726/cargo-containers-boxes-shipment-163726.jpeg?auto=compress&cs=tinysrgb&w=1200', '["https://images.pexels.com/photos/163726/cargo-containers-boxes-shipment-163726.jpeg?auto=compress&cs=tinysrgb&w=1200"]'::jsonb, '40ft reefer container Grade A — ψυχόμενο για μεγάλους όγκους και cold chain logistics. Κατάλληλο για εστιατόρια, catering, χονδρικό εμπόριο τροφίμων. Μηνιαία ενοικίαση, συντήρηση κατόπιν συνεννόησης.', '40ft reefer container Grade A — refrigerated for large volumes and cold chain logistics. Suitable for restaurants, catering, wholesale food. Monthly rent, maintenance by arrangement.', true),
  ('20ft-flat-rack', '20ft Flat Rack', 'Μεταχειρισμένο', 'Used', 220, '€220', '/μήνα', '/month', 'Έδρα μας — Ελλάδα', 'Our headquarters — Greece', 'rent'::listing_type, 'used'::stock_condition, false, '/images/containers/20ft-flat-rack.jpg', '["/images/containers/20ft-flat-rack.jpg"]'::jsonb, '20ft flat rack — χωρίς τοίχους/οροφή, ιδανικό για μηχανήματα, σωλήνες, ξυλοδέματα και out-of-gauge φορτία. Collapsible end walls. Ενοικίαση για projects και βιομηχανικές εφαρμογές.', '20ft flat rack — no side walls/roof, ideal for machinery, pipes, timber, and out-of-gauge cargo. Collapsible end walls. Rental for projects and industrial use.', true),
  ('20ft-side-opener', '20ft Side Opener', 'Grade A', 'Grade A', 3100, '€3.100', null, null, 'Έδρα μας — Ελλάδα', 'Our headquarters — Greece', 'sale'::listing_type, 'used'::stock_condition, false, '/images/containers/20ft-side-opener.jpg', '["/images/containers/20ft-side-opener.jpg","https://images.pexels.com/photos/1267338/pexels-photo-1267338.jpeg?auto=compress&cs=tinysrgb&w=1200"]'::jsonb, '20ft side opener — πλήρες άνοιγμα στη μακριά πλευρά για εύκολη φόρτωση/εκφόρτωση με forklift. Grade A, cargo worthy. Ιδανικό για retail pop-up, αποθήκη με συχνή πρόσβαση, events.', '20ft side opener — full side opening for easy forklift loading/unloading. Grade A, cargo worthy. Ideal for retail pop-up, warehouse with frequent access, events.', true),
  ('40ft-high-cube-rent', '40ft High Cube', 'Wind & Watertight', 'Wind & Watertight', 290, '€290', '/μήνα', '/month', 'Έδρα μας — Ελλάδα', 'Our headquarters — Greece', 'rent'::listing_type, 'used'::stock_condition, false, 'https://images.pexels.com/photos/163140/lifestyle-photography-logistic-manager-163140.jpeg?auto=compress&cs=tinysrgb&w=1200', '["https://images.pexels.com/photos/163140/lifestyle-photography-logistic-manager-163140.jpeg?auto=compress&cs=tinysrgb&w=1200","https://images.pexels.com/photos/1214218/pexels-photo-1214218.jpeg?auto=compress&cs=tinysrgb&w=1200"]'::jsonb, '40ft High Cube προς ενοικίαση — WWT (wind & water tight), επιπλέον ύψος για αποθήκευση και site offices. Μηνιαία μίσθωση, ελάχιστη διάρκεια κατόπιν συνεννόησης. Παράδοση από την έδρα μας σε όλη την Ελλάδα.', '40ft High Cube for rent — WWT (wind & water tight), extra height for storage and site offices. Monthly lease, minimum term by arrangement. Delivery from our base nationwide.', true)
on conflict (slug) do update set
  type = excluded.type,
  condition = excluded.condition,
  condition_en = excluded.condition_en,
  price = excluded.price,
  price_formatted = excluded.price_formatted,
  unit = excluded.unit,
  unit_en = excluded.unit_en,
  location = excluded.location,
  location_en = excluded.location_en,
  listing_type = excluded.listing_type,
  stock_condition = excluded.stock_condition,
  is_offer = excluded.is_offer,
  image = excluded.image,
  images = excluded.images,
  description = excluded.description,
  description_en = excluded.description_en,
  active = excluded.active,
  updated_at = now();
